package Challenge_105_Callable;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.List;
import java.util.ArrayList;
public class TestingFact 
{
	public static void main(String[] args) throws ExecutionException,InterruptedException
	{
		List<Future<Integer>> list=new ArrayList<>();
		try(ExecutorService service=Executors.newFixedThreadPool(3))
		{
			for(int i=1;i<=10;i++)
			{
				FactorialCalculater task1=new FactorialCalculater(i);
				list.add(service.submit(task1));
			}
			for(Future<Integer> items:list)
			{
				System.out.printf("\n Result Is : %d",items);
			}
			if(service.awaitTermination(10,TimeUnit.SECONDS))
			{
				service.shutdownNow();
			}
		}
	}
}
